- name: Check Vault is running 
  command: systemctl status vault
  ignore_errors: yes
  changed_when: false
  register: check_service
  
- debug:
    msg: "{{ check_service }}"
  when: check_service.rc == 0

- name: Stop service if service exist and running
  systemd:
    state: stopped
    name: vault
  when:
    - check_service.rc == 0
    - "'Active: active' in check_service.stdout"

- name: Gather all users which start name with Vault*
  shell:
    "cat /etc/passwd | grep 'vault[0-9]*' | cut -d: -f1"
  register: reg_users

- debug:
    msg: "{{ reg_users }}"

- name: Delete users if somebody exist above
  user:
    name: "{{ item }}"
    state: absent
    remove: yes
  with_items:
    - "{{reg_users.stdout_lines}}"
  when: reg_users.stdout != ""

- name: Delete folders and path Old version of need service
  file:
    path: /data/vault
    state: absent

- name: Delete groups if somebody exist above
  group:
    name: "{{item}}"
    state: absent
  with_items:
    - "{{reg_users.stdout_lines}}"
  when: reg_users.stdout != ""

- name: Creates directory data/vault
  file:
    path: /data/vault
    state: directory

- name: Create user Vault
  user:
    name: vault
    password_lock: yes
    shell: /sbin/nologin
    home: /data/vault 

- name: Create initial directories
  file:
    path: "{{ item }}" 
    state: directory
    owner: vault
    group: vault
    mode: 0700
  with_items:
    - /data/vault/data
    - /data/vault/etc
    - /data/vault/logs/vault

- name: Upload Vault 
  copy:
    src: "vault_1.6.1_linux_amd64.zip"
    dest: "/data/vault/"
    mode: 0700
    owner: vault
    group: vault

- name: Copy unit service document
  copy:
    src: "vault.service"
    dest: "/etc/systemd/system/"
    owner: vault
    group: vault

- name: Copy general configs to consul servers
  template:
    src: templates/{{item.name}}.j2
    dest: "{{item.path}}{{item.name}}"
  with_items:
    - {name: config.hcl, path: "/data/vault/etc/"}


- name: Install Unzip archivator
  yum:
    name: unzip
    state: present


- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: /data/vault/vault_1.6.1_linux_amd64.zip
    dest: /data/vault/
    remote_src: yes

- name: Delete zip file in a remote server
  file:
    path: /data/vault/vault_1.6.1_linux_amd64.zip
    state: absent

- name: Add permissions to the new directories and files recursively
  file:
    path: /data/vault
    owner: vault
    group: vault
    recurse: yes
    mode: 0700

- name: ADD folder executable for all users /data
  file:
    path: /data
    mode: 0777

- name: Restart and enable Service
  systemd:
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: vault

- pause:
    seconds: 10

- name: show vault status
  shell:
    /data/vault/vault status
  environment:
    VAULT_ADDR: http://127.0.0.1:8200
  ignore_errors: yes
  register: stats

- debug:
    msg="{{ stats.stdout_lines }}"

- name: Vault operate init 
  shell: /data/vault/vault operator init -key-shares=1 -key-threshold=1
  ignore_errors: yes
  environment:
    VAULT_ADDR: http://127.0.0.1:8200
  when:
    stats.rc == 2
  register: init_keys

- debug:
    msg="{{ init_keys.stdout_lines[0].split(':')[1].strip() }}" "{{ init_keys.stdout_lines[2].split(':')[1].strip() }}"
  when:
    init_keys.stdout != ""

- name: Ansible create file with secrets keys
    copy:
      dest: "/data/vault/init.file"
      content: |
        init_keys.stdout_lines[0].split(':')[1].strip()
        init_keys.stdout_lines[2].split(':')[1].strip()

- name: Rigister one unseal token
  shell: /data/vault/vault operator unseal {{init_keys.stdout_lines[0].split(':')[1].strip()}}
  environment: 
    VAULT_ADDR: http://127.0.0.1:8200

- name: Login as root
  shell: /data/vault/vault login {{init_keys.stdout_lines[2].split(':')[1].strip()}}
  environment: 
    VAULT_ADDR: http://127.0.0.1:8200

- name: Enable the database secrets engine
  shell: /data/vault/vault vault secrets enable database
  environment:
    VAULT_ADDR: http://127.0.0.1:8200
  register: res_access
  ignore_errors: yes  

- debug: msg="{{ res_access.stderr }}"

 


# - name: Configure Vault with the mongoDB plugin
#   shell: /data/vault/vault write database/config/my-mongodb-database \
#     plugin_name=mongodb-database-plugin \
#     allowed_roles="my-role" \
#     connection_url="mongodb://{{username}}:{{password}}@127.0.0.1:27017/admin" \
#     username="Dar" \
#     password="45004920"
#   environment:
#     VAULT_ADDR: http://127.0.0.1:8200


#PIDFile=/var/run/vault/vault.pid
#ExecStart=/data/vault/vault server -config=/data/vault/etc/vault_server.hcl -log-level=debug
